language: python
python: 3.5
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  user: dhosterman
  password:
    secure: yMS1g7kMQT2ssg302q/Z+NngKB9VzIBBQk5XebNUYCdRGQz6W/O4xbkN7HhzcbZoZxa9Ndkla0FE3CuZVxAUCZR0BSNaEtUOvjTNm4FhN7X3EporzqjeJRmt4GETaRbHXyXr+btkPAhtb+OMhz2f/+ZvFskFihJdnGJlLN6jxf2JluHJrFDl9K6fzD8AYqUJNzP/Y3VuKDBWF/3xzJ3XrITRcuLo+uW11V4r3kkubjZmK2AKq6JP1MClUY5pEC3AGVNMDJuh0+TTttysno3Nvdx8rEiQqVzaRx0gPrsZu77UcstedXWsYpy64zw+qF/QFCFWseRbjNFHRS0nRWNE/URo9iO1KmGFt0CyZekh80OOZbrscu7Nnb+aGNPR2DB3sRwPWBbjxRvXJRIwGEs2GWAS1SIGfwGGf32ASOV9mlxwqql08X2d6QqPsDQnHVwC9LKVKOqwxxBWeTBLa3pXljWq6wr0HEn4phozb1S9O7yIxwDHSMCRgnGYeA+TY0DTs8SBzhtzE6/VbPmrJK9xqU48TD8f1rGbwLiOvxYXQH0Qvk6Rfdy/dy4Shmb8ZuM+NfddLw2tcxuGQgO7hTYR1wnrjrz4NrWaRHNZdU/qExEvGn5kGYnfBDQpOCAeQcCtlvH7A0CR/v2wll6IreH3dgv/45WYwT/Leo/N8nwvds4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dhosterman/scorekeeper
