language: python
python: 3.5
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  user: dhosterman
  password:
    secure: jwinn6dmJ1zUprDSvdoHe3CPquN7n5a183LBNtX0S1R8ujkp4H0zLbLNXRXxKa3iP5MHxF2/BobzmqhK+V+bI06XMGwRDjp5vTUN28Sj5KQVhzNtzkySFriQNG2K5LuahIKhtaoZ+aa3jngoSYBINJO6z8b8JISzyLne7Uo6mpy43cYJuTiXH6gXekL12+2yrJPLDnH6w7Zq1s58P3owCGJEQcwzU3YmJLr77GuHr+MKkspiUK1lLgltNvMczjf7XcnTTXUbHeBa/lq9MlPvUjcP9RxPB0SFfXiKGfVnuRVc6j14FRQumwGvxaxtE0ZyevyVnnCUGMyrS8Zb+5Eciaeh9D+b0qrhzhPF7FWCXhZdotg5MV0mCFoJSAdLnk0h5ziRPoa9Sd9L2F4Fvc6Q2Z4DuJhJkEUiIeRwA9YKYENcSqoM3N0qC8+JLxxVUquji5qSKXzR0mE7uC7YUDo1RmMsxqV1go355iboyXjuRdTh/H28BhurCCep+zlbpw1cgUt8EjarFsofmRfjFRlO7YcyzmY+ZH/o+xbtp1HW+QgA/O5lWj0byACpWho8Mr5+Wr0EUe0PGCSytXmp7LsJI5Ew5JTKEq3TouL3TyvNKvW3Vuhxc1dn6Xzv1tw7knGT/80TObNtuJgSm1xlTPrF3O2bn8nzNGDfVThzZMGvCJU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dhosterman/scorekeeper
